name               = "xian-api"
main               = "src/index.js"          # modules build
compatibility_date = "2023-05-18"
account_id         = "9f5eccdd843ab1ee026067fab55893f0"


#########################
# Environment variables
#########################
[vars]
GRAPHQL_URL = "http://89.163.130.217:5000"


#########################
# Production environment
#########################
[env.production]
route = { pattern = "xian-api.poc.workers.dev", custom_domain = true }

#########################
# Optional Wrangler logs
#########################
[observability.logs]
enabled = true
