name = "xian-api"
main = "src/index.js"
compatibility_date = "2023-05-18"
account_id = "9f5eccdd843ab1ee026067fab55893f0"

[build]
command = ""

# Specify the environment
[env.production]
# Add any production-specific settings here

[env.staging]
# Add any staging-specific settings here